In [1]:
import pandas as pd
import numpy as np

pd.set_option('display.max_columns', 50)
df = pd.read_csv('city_day.csv')
print(df.shape)
display(df.head())
print(df.dtypes)

(29531, 16)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

City              str
Date              str
PM2.5         float64
PM10          float64
NO            float64
NO2           float64
NOx           float64
NH3           float64
CO            float64
SO2           float64
O3            float64
Benzene       float64
Toluene       float64
Xylene        float64
AQI           float64
AQI_Bucket        str
dtype: object

In [2]:
df['Date'] = pd.to_datetime(df['Date'])
hyd = (
    df[df['City'].str.strip().str.lower() == 'hyderabad']
    .sort_values('Date')
    .drop_duplicates(subset=['Date'])
    .set_index('Date')
)

print(hyd.index.min(), hyd.index.max())
print(hyd.head())

2015-01-04 00:00:00 2020-07-01 00:00:00
                 City  PM2.5  PM10     NO    NO2    NOx  NH3    CO   SO2  \
Date
2015-01-04  Hyderabad    NaN   NaN   3.70  17.19  20.89  NaN  0.30  2.58
2015-01-05  Hyderabad    NaN   NaN   3.61   9.69  13.30  NaN  0.23  5.19
2015-01-06  Hyderabad    NaN   NaN   4.21  22.02  26.23  NaN  0.31  9.09
2015-01-07  Hyderabad    NaN   NaN  26.08  40.08  66.15  NaN  0.53  9.03
2015-01-08  Hyderabad    NaN   NaN  10.31  33.02  43.33  NaN  0.44  8.47

               O3  Benzene  Toluene  Xylene  AQI AQI_Bucket
Date
2015-01-04  30.34     0.41     6.15    1.11  NaN        NaN
2015-01-05  31.28     0.39     7.22    0.55  NaN        NaN
2015-01-06  28.56     0.52     5.14    0.53  NaN        NaN
2015-01-07  31.08     1.92    16.35    2.14  NaN        NaN
2015-01-08  35.72     1.89    14.27    1.58  NaN        NaN

In [3]:
print(hyd.shape)
display(hyd.head())
print(hyd.head())

(2006, 15)

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
Date,,,,,,,,,,,,,,,
2015-01-04,Hyderabad,NaN,NaN,3.70,17.19,20.89,NaN,0.30,2.58,30.34,0.41,6.15,1.11,NaN,NaN
2015-01-05,Hyderabad,NaN,NaN,3.61,9.69,13.30,NaN,0.23,5.19,31.28,0.39,7.22,0.55,NaN,NaN
2015-01-06,Hyderabad,NaN,NaN,4.21,22.02,26.23,NaN,0.31,9.09,28.56,0.52,5.14,0.53,NaN,NaN
2015-01-07,Hyderabad,NaN,NaN,26.08,40.08,66.15,NaN,0.53,9.03,31.08,1.92,16.35,2.14,NaN,NaN
2015-01-08,Hyderabad,NaN,NaN,10.31,33.02,43.33,NaN,0.44,8.47,35.72,1.89,14.27,1.58,NaN,NaN

                 City  PM2.5  PM10     NO    NO2    NOx  NH3    CO   SO2  \
Date
2015-01-04  Hyderabad    NaN   NaN   3.70  17.19  20.89  NaN  0.30  2.58
2015-01-05  Hyderabad    NaN   NaN   3.61   9.69  13.30  NaN  0.23  5.19
2015-01-06  Hyderabad    NaN   NaN   4.21  22.02  26.23  NaN  0.31  9.09
2015-01-07  Hyderabad    NaN   NaN  26.08  40.08  66.15  NaN  0.53  9.03
2015-01-08  Hyderabad    NaN   NaN  10.31  33.02  43.33  NaN  0.44  8.47

               O3  Benzene  Toluene  Xylene  AQI AQI_Bucket
Date
2015-01-04  30.34     0.41     6.15    1.11  NaN        NaN
2015-01-05  31.28     0.39     7.22    0.55  NaN        NaN
2015-01-06  28.56     0.52     5.14    0.53  NaN        NaN
2015-01-07  31.08     1.92    16.35    2.14  NaN        NaN
2015-01-08  35.72     1.89    14.27    1.58  NaN        NaN

In [5]:
missing = hyd.isna().mean().sort_values(ascending=False)
display((missing * 100).round(1).to_frame('missing_percent'))
hyd.head()

            missing_percent
NH3                    17.9
PM10                   17.7
Benzene                 6.3
Toluene                 6.3
Xylene                  6.3
AQI                     6.3
AQI_Bucket              6.3
PM2.5                   5.7
NO                      1.4
NO2                     1.4
SO2                     1.3
O3                      1.3
NOx                     0.3
CO                      0.2
City                    0.0

,City,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
Date,,,,,,,,,,,,,,,
2015-01-04,Hyderabad,NaN,NaN,3.70,17.19,20.89,NaN,0.30,2.58,30.34,0.41,6.15,1.11,NaN,NaN
2015-01-05,Hyderabad,NaN,NaN,3.61,9.69,13.30,NaN,0.23,5.19,31.28,0.39,7.22,0.55,NaN,NaN
2015-01-06,Hyderabad,NaN,NaN,4.21,22.02,26.23,NaN,0.31,9.09,28.56,0.52,5.14,0.53,NaN,NaN
2015-01-07,Hyderabad,NaN,NaN,26.08,40.08,66.15,NaN,0.53,9.03,31.08,1.92,16.35,2.14,NaN,NaN
2015-01-08,Hyderabad,NaN,NaN,10.31,33.02,43.33,NaN,0.44,8.47,35.72,1.89,14.27,1.58,NaN,NaN

In [6]:
wanted = ['AQI', 'PM2.5', 'PM10', 'NO2', 'CO', 'O3']
hyd = hyd[wanted].copy()

for column in wanted:
    hyd[column] = pd.to_numeric(hyd[column], errors='coerce')

print(hyd.head())
print(hyd.describe().T)

            AQI  PM2.5  PM10    NO2    CO     O3
Date
2015-01-04  NaN    NaN   NaN  17.19  0.30  30.34
2015-01-05  NaN    NaN   NaN   9.69  0.23  31.28
2015-01-06  NaN    NaN   NaN  22.02  0.31  28.56
2015-01-07  NaN    NaN   NaN  40.08  0.53  31.08
2015-01-08  NaN    NaN   NaN  33.02  0.44  35.72
        count        mean        std    min      25%     50%       75%     max
AQI    1880.0  109.207447  53.142709  22.00  75.0000  104.00  130.0000  737.00
PM2.5  1891.0   47.035357  38.522589   4.83  25.7900   42.00   61.4150  571.02
PM10   1651.0   91.931532  40.476131  10.54  61.5250   94.48  117.4450  485.88
NO2    1978.0   28.386754  15.924444   0.62  15.4775   25.57   38.8675   92.33
CO     2001.0    0.590780   0.515106   0.00   0.3200    0.57    0.7700    8.83
O3     1980.0   33.611005  14.936788   0.02  22.5150   32.11   43.1125  107.68

In [8]:
full_dates = pd.date_range(hyd.index.min(), hyd.index.max(), freq='D')
hyd = hyd.reindex(full_dates)
hyd.index.name = 'Date'
print(hyd.head())

            AQI  PM2.5  PM10    NO2    CO     O3
Date
2015-01-04  NaN    NaN   NaN  17.19  0.30  30.34
2015-01-05  NaN    NaN   NaN   9.69  0.23  31.28
2015-01-06  NaN    NaN   NaN  22.02  0.31  28.56
2015-01-07  NaN    NaN   NaN  40.08  0.53  31.08
2015-01-08  NaN    NaN   NaN  33.02  0.44  35.72

In [9]:
missing_before = hyd.isna().sum()
print(missing_before)

AQI      126
PM2.5    115
PM10     355
NO2       28
CO         5
O3        26
dtype: int64

In [18]:
hyd = hyd.interpolate(method='time', limit=2)

hyd = hyd.dropna(subset=['AQI'])
missing_after = hyd.isna().sum()

hyd.head()

print(pd.DataFrame({
    'before': missing_before,
    'after': missing_after
}))

print(hyd.head())

       before  after
AQI       126      0
PM2.5     115      0
PM10      355    229
NO2        28      0
CO          5      0
O3         26      0
              AQI    PM2.5  PM10    NO2    CO     O3
Date
2015-03-31  120.0  47.0300   NaN  16.94  0.81  25.13
2015-04-01  112.0  40.6200   NaN  13.18  0.81  34.19
2015-04-02  117.8  43.1825   NaN  14.34  0.85  31.97
2015-04-03  123.6  45.7450   NaN  22.86  1.07  36.15
2015-04-06  141.0  83.0000   NaN  12.91  0.89  33.67

In [19]:
assert hyd.index.is_monotonic_increasing
assert not hyd.index.duplicated().any()
assert hyd['AQI'].notna().all()
negative_counts = (hyd.select_dtypes('number') < 0).sum()
print(negative_counts)
print(hyd.shape)

AQI      0
PM2.5    0
PM10     0
NO2      0
CO       0
O3       0
dtype: int64
(1897, 6)

In [22]:
hyd.to_csv('..\data\processed\hyderabad_aqi.csv')
print('Saved:', '../data/processed/hyderabad_aqi.csv')

Saved: ../data/processed/hyderabad_aqi.csv